# CLI Tools
brew "git"
brew "stow"
brew "neovim"
brew "fzf"
brew "ripgrep"
brew "fd"
brew "tree"
brew "htop"
brew "jq"
brew "curl"
brew "wget"

# Fonts
cask "font-monaspace"

# Applications
cask "ghostty"
cask "google-chrome"
cask "slack"
